language: node_js
sudo: false
node_js:
  - 11.13.0
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
stages:
  - test
  - build
  - lint
jobs:
  include:
    - stage: test
      script: yarn test:coveralls
    - script: yarn check:formatting
    - script: yarn e2e
    - stage: build
      script: yarn build
    - stage: build docker
      deploy:
        provider: script
        script: bash server/build-docker.sh
        on:
          branch: master
